# Generated by Django 5.1.7 on 2025-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_description',
            field=models.TextField(null=True, verbose_name='Cart Item Description'),
        ),
    ]
